const EStyleSheet = require("react-native-extended-stylesheet");
import { height, width } from '../../utils/Scalaing';

export const stylesExpanded = EStyleSheet.create({
    container: {
       backgroundColor: '#f3f3f3',
       paddingTop: 20,
       paddingHorizontal: 5,
       paddingVertical: 10,
    },
    item_container: {
       flexDirection: 'row',
       paddingBottom: 5,
       borderWidth: 1,
       marginBottom: 2,
       paddingBottom: 20,
       paddingHorizontal: 10,
       marginTop: 4,
       borderBottomWidth: 1,
       backgroundColor: '#fff',
       height: width < height ? height * 0.15 : height * 0.35,
    },
    item_container_one: {
       flex: 2,
       position: 'relative',
       paddingTop: 20,
    },
    item_container_two: {
       flex: 4,
       paddingTop: 15,
       paddingHorizontal: 10,
       justifyContent: 'center',
       paddingTop: 15,
       paddingLeft: 10,
    },
    item_container_three: {
       flex: 2,
       paddingTop: 15,
    },
    selected_type_conatiner: {
       backgroundColor: '#fff',
       borderRadius: 1,
       borderWidth: 2,
       borderColor: '#d9d9d9',
    },
    bottom_container: {
       flex: 1,
       justifyContent: 'center',
       flexDirection: 'row',
    },
    item_image_title: {
       position: 'absolute',
       zIndex: 8,
       color: 'gray',
       fontWeight: 'bold',
       paddingLeft: 10,
       paddingTop: 20,
    },
    item_image: {
       flex: 1,
       height: null,
       width: null,
       resizeMode: 'cover',
    },
    item_title: {
       fontSize: 14,
    },
    item_chef: {
       color: 'gray',
       fontSize: 10,
    },
    item_category: {
       backgroundColor: '#56b783',
       color: 'white',
       width: 70,
       textAlign: 'center',
       marginTop: 5,
       paddingVertical: 2,
       borderRadius: 2,
       fontSize: 10,
    },
    options_text: {
       color: '#3fa4fd',
       textAlign: 'right',
       fontSize: 12,
       paddingBottom: 10,
    },
    item_details: {
       textAlign: 'right',
    },
    price: {
       flex: 1,
       justifyContent: 'flex-start',
       alignItems: 'center',
       flexDirection: 'row',
    },
    add_to_cart_container: {
       flex: 1,
       justifyContent: 'flex-end',
       alignItems: 'center',
       flexDirection: 'row',
    },
    button: {
       backgroundColor: '#3fa4ff',
       paddingVertical: 5,
       paddingHorizontal: 15,
    },
    add_to_card_text: {
       color: 'white',
       fontSize: 14,
    },
    price_text: {
       fontSize: 20,
       fontWeight: 'bold',
    },
    details: {
       justifyContent: 'center',
    },
    type_container: {
       height: height * 0.1,
       flexDirection: 'row',
    },
    type_container_right: {
       flex: 1,
       flexDirection: 'row',
       justifyContent: 'center',
       paddingVertical: 15,
    },
    type_button: {
       flexDirection: 'row',
       alignItems: 'center',
       justifyContent: 'space-between',
       backgroundColor: '#f1f1f1',
       paddingHorizontal: 10,
    },
    done_container: {
       backgroundColor: '#3fa4ff',
       borderRadius: 50,
       justifyContent: 'center',
       alignItems: 'center',
       marginLeft: 5,
       height: 20,
       width: 20,
    },
    item_three_upper: {
       justifyContent: 'center',
       alignItems: 'flex-end',
       flex: 1,
    },
    item_three_lower: {
       flex: 1,
       justifyContent: 'flex-end',
       alignItems: 'flex-end',
    },
 });

export const stylesCollapsed = EStyleSheet.create({
   item_container: {
      flexDirection: 'row',
      paddingBottom: 5,
      marginBottom: 2,
      paddingBottom: 20,
      paddingHorizontal: 10,
      marginTop: 4,
      borderBottomWidth: 1,
      backgroundColor: '#fff',
      borderBottomColor: '#ececec',
      height: width < height ? height * 0.15 : height * 0.35,
   },
   item_container_one: {
      flex: 2,
      position: 'relative',
      paddingTop: 20,
   },
   item_container_two: {
      flex: 4,
      paddingTop: 15,
      paddingHorizontal: 10,
      justifyContent: 'center',
      paddingTop: 15,
      paddingLeft: 10,
   },
   item_container_three: {
      flex: 2,
      paddingTop: 15,
   },
   bottom_container: {
      flex: 1,
      justifyContent: 'center',
      flexDirection: 'row',
   },
   item_image_title: {
      position: 'absolute',
      zIndex: 8,
      color: 'gray',
      fontWeight: 'bold',
   },
   item_image: {
      flex: 1,
      height: null,
      width: null,
      resizeMode: 'cover',
   },
   item_title: {
      fontSize: '$xxs',
   },
   item_chef: {
      color: 'gray',
      fontSize: '$xxxs',
   },
   item_category: {
      backgroundColor: '#56b783',
      color: 'white',
      width: 70,
      textAlign: 'center',
      marginTop: 5,
      paddingVertical: 2,
      borderRadius: 2,
      fontSize: '$xxs',
   },
   options_text: {
      color: '#3fa4fd',
      textAlign: 'right',
      fontSize: '$xs',
   },
   item_details: {
      textAlign: 'right',
      fontSize: '$xxs',
   },
   price: {
      flex: 1,
      justifyContent: 'flex-start',
      alignItems: 'center',
      flexDirection: 'row',
   },
   add_to_cart_container: {
      flex: 1,
      justifyContent: 'flex-end',
      alignItems: 'center',
      flexDirection: 'row',
   },
   button: {
      backgroundColor: '#3fa4ff',
      paddingVertical: 5,
      paddingHorizontal: 15,
   },
   add_to_card_text: {
      color: 'white',
      fontSize: 14,
   },
   price_text: {
      fontSize: 20,
      fontWeight: 'bold',
   },
   details: {
      justifyContent: 'center',
   },
   type_container: {
      height: height * 0.1,
      flexDirection: 'row',
   },
   type_container_right: {
      flex: 1,
      flexDirection: 'row',
      justifyContent: 'center',
      paddingVertical: 15,
   },
   type_button: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#f1f1f1',
      paddingHorizontal: 10,
   },
   done_container: {
      backgroundColor: '#3fa4ff',
      borderRadius: 50,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 5,
      height: 20,
      width: 20,
   },
   item_three_upper: {
      justifyContent: 'flex-end',
      alignItems: 'flex-start',
      flex: 1,
      flexDirection: 'row',
   },
   item_three_lower: {
      flex: 1,
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
   },
});