import {
  GET_MENU,
  COMBO_PRODUCT,
  CUSTOMIZABLE_PRODUCT,
  INVENTORY_PRODUCT,
  SIMPLE_PRODUCT,
} from './queries';

import { CREATE_CUSTOMER, UPDATE_CART, CREATE_CART } from './mutations';

import { CUSTOMER } from './subscriptions';

export {
  CUSTOMER,
  GET_MENU,
  COMBO_PRODUCT,
  CUSTOMIZABLE_PRODUCT,
  INVENTORY_PRODUCT,
  SIMPLE_PRODUCT,
  CREATE_CUSTOMER,
  CREATE_CART,
  UPDATE_CART,
};
